### PR TITLE
Admin Can Cancel a Game [ #42 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/42 )

### LINKED ISSUE #42: As an Admin I can cancel the game
# Admin Can Cancel Game

## Description
The admin can now cancel the game. To cancel a game, the admin needs to click the cancel game button. Cancelling the game ends the game for all players who were in the game. 

## Acceptance criteria
- The game admin can cancel a game.
- When the admin clicks the button to cancel a game, the game cancels.
- When the game cancels, all the players that were in the game are removed from the game.

## Expected Story Points

- 2  story points

### PR DESCRIPTION
**Pull request by Yishai-Bass**
closes #42 
# Admin Can Cancel a Game

## Description
The admin player in a room can cancel the game and all players are sent to the landing page.

## Acceptance criteria
- The cancel button appears for an admin player
- The cancel button does not appear for a regular player
- When the Admin clicks the cancel button, all players are sent to the landing page

## Story Points

- 3  story points

### CODE REVIEW

**Comment by jacob-sacks** [comment]
Very well-implemented user story! Just a note, the game is running quite slowly. Maybe consider web sockets to fix this.

**Comment by Yishai-Bass** [comment]
> Very well-implemented user story! Just a note, the game is running quite slowly. Maybe consider web sockets to fix this.

Okay thank you @jacob-sacks, I also noticed this but did not know what to do about it. I will look into this.

**Review by jacob-sacks — APPROVED** [review]
Functionality: Approved
The updated code in waitingRoom.js introduces a cancel game button and makes various improvements to the existing functionality. These changes enhance the user experience and align with the intended functionality of the waiting room.

Complexity: Approved
The complexity introduced with the new cancel game functionality and other changes is reasonable and aligns with the existing code structure.

Tests: Approved 
Jest Test Cases are implemented. Testing done to make sure that when the admin cancels the game, all players are sent back to landing page.

Naming: Approved
The function names and variable names, such as cancelGameButton and buttonContainer, are clear and descriptive, which enhances code readability.

Style: Approved
The coding style in this file is consistent and easy to follow. The changes to the button container align with the existing style.

Documentation: N/A
No additional documentation is necessary for this file.

**Comment by Yishai-Bass** [comment]
> Functionality: Approved The updated code in waitingRoom.js introduces a cancel game button and makes various improvements to the existing functionality. These changes enhance the user experience and align with the intended functionality of the waiting room.
> 
> Complexity: Approved The complexity introduced with the new cancel game functionality and other changes is reasonable and aligns with the existing code structure.
> 
> Tests: Approved Jest Test Cases are implemented. Testing done to make sure that when the admin cancels the game, all players are sent back to landing page.
> 
> Naming: Approved The function names and variable names, such as cancelGameButton and buttonContainer, are clear and descriptive, which enhances code readability.
> 
> Style: Approved The coding style in this file is consistent and easy to follow. The changes to the button container align with the existing style.
> 
> Documentation: N/A No additional documentation is necessary for this file.

Thank you for the thorough review

**Pull request merged**
